.github/workflows/publish.yaml
=> Correct reusable workflow path

background/src/constants/constants.js, background/src/main.js, background/src/wallet/wallet.js, content-scripts/src/injectsdk.ts, docs/api.md, examples/daily-reward-dapp/src/App.tsx, packages/chrono-sdk/src/chrono-wallet.ts, packages/chrono-sdk/src/handler.ts, popup/src/api/background.js, popup/src/views/Confirmation.vue
=> feat: implement site allowance

background/src/api/graphql.js, background/src/constants/constants.js, background/src/main.js, background/src/wallet/wallet.js, content-scripts/src/injectsdk.ts, docs/api.md, examples/daily-reward-dapp/src/App.tsx, packages/chrono-sdk/src/chrono-wallet.ts, pnpm-lock.yaml, popup/package.json, popup/src/App.vue, popup/src/components/SignedInHeader.vue, popup/src/components/buttons/NetworkSelector.vue, popup/src/constants/constants.js, popup/src/store/index.js, popup/src/store/modules/account.js, popup/src/store/modules/network.ts, popup/src/views/InitiateMnemonic.vue, popup/src/views/Login.vue, popup/tsconfig.json
=> Switch network

background/package.json, background/src/utils/aes256.js, pnpm-lock.yaml, popup/package.json, popup/src/api/background.js, popup/src/components/AccountManager.vue, popup/src/utils/aes256.js, popup/src/views/Initiate.vue, popup/src/views/Login.vue
This update fixes the issue where keccak256 wasn't working, which caused problems with logging in, initialization, and other related processes.
=> fix: replace keccak256 with @noble/hashes

.github/workflows/build.yaml
=> ci: upload artifact

background/.eslintrc.json, background/package.json, background/src/event.ts, background/src/main.js, background/src/wallet/wallet.js, content-scripts/src/injectsdk.ts, examples/daily-reward-dapp/src/App.tsx, packages/chrono-sdk/src/chrono-wallet.ts, packages/chrono-sdk/src/event.ts, packages/chrono-sdk/src/handler.ts, pnpm-lock.yaml, popup/src/api/background.js, popup/src/store/modules/network.ts
It resolves #28 
It introduces the below APIs:
```typescript
subscribe(event: EventType, handler: EventHandler): void;
unsubscribe(event: EventType, handler: EventHandler): void;
```
=> feat: provide `chronoWallet.subscribe` API

.npmrc, examples/daily-reward-dapp/package.json, examples/daily-reward-dapp/src/Agent.tsx, packages/chrono-sdk/package.json, packages/chrono-sdk/src/chrono-wallet.ts, packages/chrono-sdk/tsconfig.json, pnpm-lock.yaml
=> feat(chrono-sdk): change parameter type to action type

popup/src/api/background.ts, popup/src/components/AccountManager.vue, popup/src/components/SignedInHeader.vue, popup/src/components/buttons/NetworkSelector.vue, popup/src/stores/account.ts, popup/src/stores/network.ts, popup/src/types.ts, popup/src/views/Index.vue
It resolves #49 
> [!WARNING]
> It should re-install (remove and install) chrono.
=> feat(popup): make explorer link configurable

background/src/wallet/wallet.ts, examples/daily-reward-dapp/package.json, examples/daily-reward-dapp/src/App.tsx, examples/daily-reward-dapp/src/main.tsx, packages/chrono-sdk/package.json, packages/chrono-sdk/src/chrono-wallet.ts, packages/chrono-sdk/src/event.ts, packages/chrono-sdk/src/hooks/index.ts, packages/chrono-sdk/src/hooks/useAccounts.ts, packages/chrono-sdk/src/hooks/useConnect.ts, pnpm-lock.yaml, popup/src/views/Confirmation.vue
=> feat: introduce hooks

extension/_locales/en/messages.json, extension/_locales/ko/messages.json
It removes unnecessary description and translate description part to Korean.
=> chore: remove unnecessary description

background/src/api/graphql.ts, popup/src/components/AccountManager.vue, popup/src/components/buttons/AccountSelector.vue, popup/src/stores/account.ts, popup/src/types.ts, popup/src/views/Index.vue
=> feat: remove activation part

README.md, docs/index.md
=> docs: style readme

background/package.json, background/src/api/graphql.ts, background/src/controllers/connection.ts, background/src/wallet/wallet.ts, pnpm-lock.yaml
=> Remove tx factory with GraphQL

package.json
=> chore: version up to 1.0.5

extension/manifest.json, extension/manifest.prod.json
=> chore: version up in extension manifest

examples/daily-reward-dapp/src/CreateAvatarButton.tsx
=> bug fix: in `daily-reward-dapp` example

docs/README.md, docs/user/install.md
Fix download url in document and add README.
=> fix download url in document

background/package.json, background/rollup.config.js, background/src/constants/constants.ts, background/src/wallet/wallet.ts, pnpm-lock.yaml, popup/src/api/background.ts, popup/src/components/AccountManager.vue, popup/src/components/buttons/AccountSelector.vue, popup/src/constants/constants.ts, popup/src/stores/account.ts, popup/src/types.ts, popup/src/views/Confirmation.vue
This PR is a port of https://github.com/tx0x/chrono/pull/10.
it enables AWS KMS as a signer on chrono.
=> Support AWS/KMS account

examples/daily-reward-dapp/src/index.d.ts, packages/chrono-sdk/jsr.json, packages/chrono-sdk/package.json, packages/chrono-sdk/src/chrono-wallet.ts
Provides API to sign action with its plain value
=> Add signWithPlainValue method

background/src/wallet/wallet.ts, packages/chrono-sdk/jsr.json, packages/chrono-sdk/package.json, packages/chrono-sdk/src/index.ts
Fixed error where type mismatches
=> Fix bug in sign

background/src/wallet/wallet.ts, pnpm-lock.yaml, popup/package.json, popup/src/views/Send.vue
This PR fixes UI bug and internal wallet module errors, during transferring NCG.
=> Bugfix: transfer NCG
